const mainCategories = [
    { id: 1, name: "Ev Dekorasyonu", img: "https://via.placeholder.com/150?text=Ev+Dekorasyonu", link: "/kategori/ev-dekorasyonu" },
    { id: 2, name: "Elektronik", img: "https://via.placeholder.com/150?text=Elektronik", link: "/kategori/elektronik" },
    { id: 3, name: "Anne & Bebek", img: "https://via.placeholder.com/150?text=Anne+%26+Bebek", link: "/kategori/anne-bebek" },
    { id: 4, name: "Moda", img: "https://via.placeholder.com/150?text=Moda", link: "/kategori/moda" },
    { id: 5, name: "Spor & Outdoor", img: "https://via.placeholder.com/150?text=Spor+%26+Outdoor", link: "/kategori/spor-outdoor" },
    { id: 6, name: "Kozmetik & Bakım", img: "https://via.placeholder.com/150?text=Kozmetik+%26+Bakım", link: "/kategori/kozmetik-bakim" },
    { id: 7, name: "Kitap & Hobi", img: "https://via.placeholder.com/150?text=Kitap+%26+Hobi", link: "/kategori/kitap-hobi" },
    { id: 8, name: "Oyun & Konsol", img: "https://via.placeholder.com/150?text=Oyun+%26+Konsol", link: "/kategori/oyun-konsol" },
    { id: 9, name: "Saat & Aksesuar", img: "https://via.placeholder.com/150?text=Saat+%26+Aksesuar", link: "/kategori/saat-aksesuar" },
    { id: 10, name: "Ayakkabı & Çanta", img: "https://via.placeholder.com/150?text=Ayakkabı+%26+Çanta", link: "/kategori/ayakkabi-canta" },
    { id: 11, name: "Ev Aletleri", img: "https://via.placeholder.com/150?text=Ev+Aletleri", link: "/kategori/ev-aletleri" },
    { id: 12, name: "Gıda & Süpermarket", img: "https://via.placeholder.com/150?text=Gıda+%26+Süpermarket", link: "/kategori/gida-supermarket" },
    { id: 13, name: "Mutfak Gereçleri", img: "https://via.placeholder.com/150?text=Mutfak+Gereçleri", link: "/kategori/mutfak-gerecleri" },
    { id: 14, name: "Ofis & Kırtasiye", img: "https://via.placeholder.com/150?text=Ofis+%26+Kırtasiye", link: "/kategori/ofis-kirtasiye" },
    { id: 15, name: "Çocuk Giyim", img: "https://via.placeholder.com/150?text=Çocuk+Giyim", link: "/kategori/cocuk-giyim" },
    { id: 16, name: "Takı & Mücevher", img: "https://via.placeholder.com/150?text=Takı+%26+Mücevher", link: "/kategori/taki-mucevher" },
    { id: 17, name: "Pet Shop", img: "https://via.placeholder.com/150?text=Pet+Shop", link: "/kategori/pet-shop" },
    { id: 18, name: "Kış Sporları", img: "https://via.placeholder.com/150?text=Kış+Sporları", link: "/kategori/kis-sporlari" },
    { id: 19, name: "Tatil & Seyahat", img: "https://via.placeholder.com/150?text=Tatil+%26+Seyahat", link: "/kategori/tatil-seyahat" },
    { id: 20, name: "Oto Aksesuar", img: "https://via.placeholder.com/150?text=Oto+Aksesuar", link: "/kategori/oto-aksesuar" },
    { id: 21, name: "Fitness & Sağlık", img: "https://via.placeholder.com/150?text=Fitness+%26+Sağlık", link: "/kategori/fitness-saglik" },
    { id: 22, name: "Kışlık Giyim", img: "https://via.placeholder.com/150?text=Kışlık+Giyim", link: "/kategori/kislik-giyim" },
    { id: 23, name: "Bebek Oyuncakları", img: "https://via.placeholder.com/150?text=Bebek+Oyuncakları", link: "/kategori/bebek-oyuncaklari" },
    { id: 24, name: "Akıllı Ev Sistemleri", img: "https://via.placeholder.com/150?text=Akıllı+Ev+Sistemleri", link: "/kategori/akilli-ev-sistemleri" },
    { id: 25, name: "Plaj Giyim", img: "https://via.placeholder.com/150?text=Plaj+Giyim", link: "/kategori/plaj-giyim" },
    { id: 26, name: "Mobilya", img: "https://via.placeholder.com/150?text=Mobilya", link: "/kategori/mobilya" },
    { id: 27, name: "Beyaz Eşya", img: "https://via.placeholder.com/150?text=Beyaz+Eşya", link: "/kategori/beyaz-esya" },
    { id: 28, name: "Şapka & Aksesuar", img: "https://via.placeholder.com/150?text=Şapka+%26+Aksesuar", link: "/kategori/sapka-aksesuar" },
    { id: 29, name: "Elektrikli Scooter", img: "https://via.placeholder.com/150?text=Elektrikli+Scooter", link: "/kategori/elektrikli-scooter" },
    { id: 30, name: "Saç Bakım", img: "https://via.placeholder.com/150?text=Saç+Bakım", link: "/kategori/sac-bakim" },
];

export default mainCategories;
